### PR TITLE
feat/improved-enemy-mechanics-music-new-player-sprite

### PR DESCRIPTION
**Pull request by batmanual9595**
I added a lot of stuff, including:
three new enemies
- an enemy that dashes at you when hit with your light
- an enemy that follows an invisible point that follows you
- an enemy that mimics player movements
I also added enemy difficulty scaling. The numbers are really low since enemies scale really fast. Maybe someone could redo the math so it scales smoother?
I also added a new player sprite (a mouse), as well as a physical flashlight that rotates with your mouse. I also added a basic music loop.

Note: this also has enemy spawn code. I couldn't get it to work. Maybe someone else could?
Note pt 2: I added a don't destroy script, which also gives everything it's attached to a unique ID. Don't worry about it, just thought I should mention it here in case anyone was wondering.

### CODE REVIEW

**Comment by batmanual9595** [comment]
Whoever reviews this, be thorough. I feel like there could be a lot of bugs w this that I didn't find. Also maybe adjust values and see what works best.

**Comment by batmanual9595** [comment]
Oh I also made the corridors wider so it's easier to dodge enemies.

**Review by mud-ali — CHANGES_REQUESTED** [review]
- [X] All three enemies appear
- [X] all of them chase you
- [X] Music is fire 
- [X] Player sprite + flashlight lgtm

Changes to be made:
- [x] not all the enemies do damage to the player
- [ ] some stylistic issues with var naming (ex: underscore prefix for private vars)
- [x] idt enemy spawning seems to work but also i dont think its essential at this point. the game is challenging enough with the current enemies chasing you around
- [x] i dont really observe a difference with enemy difficulty scaling but gameplay seems okay rn regardless

**Review by mud-ali — APPROVED** [review]
all good

**Pull request merged**
